# %% [markdown]
# # 00 - Data profiling (Phase 0)
#
# Goal: understand the raw Olist tables before making any cleaning or modelling decision.
# For every table: row count, columns, types, nulls, distinct values, value ranges.
# Then: primary key candidates, relationships between tables, and the known traps.
#
# Input : data/processed/olist.duckdb (built by `python run_sql.py`)
# Output: docs/profiling_report.md (generated - do not edit by hand)
#
# Run as a script (`python notebooks/00_data_profiling.py`) or cell by cell in VS Code.
# This script only READS the data. It changes nothing.

# %%
import sys
from pathlib import Path

import duckdb

# Windows consoles default to a legacy code page; force UTF-8 so Portuguese text prints safely.
sys.stdout.reconfigure(encoding="utf-8")

try:
    ROOT = Path(__file__).resolve().parents[1]
except NameError:  # running cell by cell: fall back to the working directory
    ROOT = Path.cwd() if (Path.cwd() / "sql").exists() else Path.cwd().parent

DB_PATH = ROOT / "data" / "processed" / "olist.duckdb"
REPORT_PATH = ROOT / "docs" / "profiling_report.md"

con = duckdb.connect(str(DB_PATH), read_only=True)

TABLES = [
    "orders",
    "order_items",
    "order_payments",
    "order_reviews",
    "customers",
    "sellers",
    "products",
    "geolocation",
    "category_translation",
]

report = []  # lines of the markdown report


# %%
def fmt(value) -> str:
    """Format a value for a markdown table cell."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, int):
        return f"{value:,}"
    return str(value).replace("\r", " ").replace("\n", " ").replace("|", "/")


def shorten(value, max_len: int = 40):
    """Cut long example values (e.g. review texts) so the table stays readable."""
    if value is None:
        return None
    text = str(value)
    return text if len(text) <= max_len else text[: max_len - 3] + "..."


def md_table(headers, rows) -> list:
    """Build a markdown table from a header list and a list of rows."""
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(fmt(v) for v in row) + " |" for row in rows]
    return lines + [""]


def scalar(sql: str):
    """Run a query that returns one single value."""
    return con.execute(sql).fetchone()[0]


# %% [markdown]
# ## 1. Table overview: how many rows and columns does each table have?

# %%
overview = []
for table in TABLES:
    n_rows = scalar(f"SELECT count(*) FROM raw.{table}")
    n_cols = len(con.execute(f"DESCRIBE raw.{table}").fetchall())
    overview.append((f"raw.{table}", n_rows, n_cols))

report += ["# Data profiling report (raw Olist tables)", ""]
report += [
    "Generated by `notebooks/00_data_profiling.py` from `data/processed/olist.duckdb` "
    f"(DuckDB {duckdb.__version__}). Do not edit by hand: re-run the script instead.",
    "",
    "## 1. Table overview",
    "",
]
report += md_table(["table", "rows", "columns"], overview)


# %% [markdown]
# ## 2. Column profile: nulls, distinct values, example and range for every column
#
# One query per table. For each column we compute:
# - nulls    = total rows minus rows where the column is filled
# - distinct = number of different values (a column with distinct = rows is a key candidate)
# - example  = the first filled value in file order, so the dictionary shows what the data looks like
#              (arg_min over rowid instead of any_value: any_value can return a different row on
#              every run, and a generated report must be identical when re-run)
# - min/max  = only for numbers and dates (for text the alphabetical min/max is meaningless)

# %%
report += ["## 2. Column profile", ""]

for table in TABLES:
    n_rows = scalar(f"SELECT count(*) FROM raw.{table}")
    columns = [(row[0], row[1]) for row in con.execute(f"DESCRIBE raw.{table}").fetchall()]

    parts = []
    for name, _ in columns:
        parts.append(
            f'count(*) - count("{name}"), count(DISTINCT "{name}"), '
            f'arg_min("{name}", rowid) FILTER (WHERE "{name}" IS NOT NULL), min("{name}"), max("{name}")'
        )
    result = con.execute(f"SELECT {', '.join(parts)} FROM raw.{table}").fetchone()

    rows = []
    for i, (name, dtype) in enumerate(columns):
        nulls, distinct, example, vmin, vmax = result[i * 5 : i * 5 + 5]
        is_text = dtype == "VARCHAR"
        rows.append(
            (
                name,
                dtype,
                nulls,
                f"{nulls / n_rows:.2%}",
                distinct,
                shorten(example),
                "" if is_text else str(vmin),
                "" if is_text else str(vmax),
            )
        )

    report += [f"### raw.{table} ({n_rows:,} rows)", ""]
    report += md_table(["column", "type", "nulls", "null %", "distinct", "example", "min", "max"], rows)


# %% [markdown]
# ## 3. Primary key candidates
#
# A primary key must identify exactly one row. Test: number of rows = number of distinct key values.
# We test the "obvious" key of each table, plus a few alternatives where the obvious one fails.

# %%
KEY_CANDIDATES = [
    ("orders", ["order_id"]),
    ("customers", ["customer_id"]),
    ("customers", ["customer_unique_id"]),
    ("order_items", ["order_id", "order_item_id"]),
    ("order_payments", ["order_id", "payment_sequential"]),
    ("order_reviews", ["review_id"]),
    ("order_reviews", ["order_id"]),
    ("order_reviews", ["review_id", "order_id"]),
    ("sellers", ["seller_id"]),
    ("products", ["product_id"]),
    ("category_translation", ["product_category_name"]),
    ("geolocation", ["geolocation_zip_code_prefix"]),
]

key_rows = []
for table, key in KEY_CANDIDATES:
    cols = ", ".join(key)
    n_rows = scalar(f"SELECT count(*) FROM raw.{table}")
    n_keys = scalar(f"SELECT count(*) FROM (SELECT DISTINCT {cols} FROM raw.{table})")
    key_rows.append((f"raw.{table}", cols, n_rows, n_keys, n_rows == n_keys))

report += ["## 3. Primary key candidates", ""]
report += md_table(["table", "candidate key", "rows", "distinct keys", "unique?"], key_rows)


# %% [markdown]
# ## 4. Relationships between tables
#
# For every foreign key (child column pointing to a parent table) we count:
# - child keys without parent: values in the child that do not exist in the parent ("orphans")
# - parents without child: parent rows that no child row points to (e.g. orders without items)
# - max children per parent: tells us whether the relationship is 1:1 or 1:many

# %%
RELATIONSHIPS = [
    # (child table, child column, parent table, parent column)
    ("orders", "customer_id", "customers", "customer_id"),
    ("order_items", "order_id", "orders", "order_id"),
    ("order_payments", "order_id", "orders", "order_id"),
    ("order_reviews", "order_id", "orders", "order_id"),
    ("order_items", "product_id", "products", "product_id"),
    ("order_items", "seller_id", "sellers", "seller_id"),
    ("products", "product_category_name", "category_translation", "product_category_name"),
    ("customers", "customer_zip_code_prefix", "geolocation", "geolocation_zip_code_prefix"),
    ("sellers", "seller_zip_code_prefix", "geolocation", "geolocation_zip_code_prefix"),
]

rel_rows = []
for child, fk, parent, pk in RELATIONSHIPS:
    orphans = scalar(
        f"""
        SELECT count(*)
        FROM (SELECT DISTINCT {fk} AS k FROM raw.{child} WHERE {fk} IS NOT NULL) c
        WHERE NOT EXISTS (SELECT 1 FROM raw.{parent} p WHERE p.{pk} = c.k)
        """
    )
    childless = scalar(
        f"""
        SELECT count(*)
        FROM (SELECT DISTINCT {pk} AS k FROM raw.{parent}) p
        WHERE NOT EXISTS (SELECT 1 FROM raw.{child} c WHERE c.{fk} = p.k)
        """
    )
    max_children = scalar(
        f"SELECT max(n) FROM (SELECT count(*) AS n FROM raw.{child} WHERE {fk} IS NOT NULL GROUP BY {fk})"
    )
    rel_rows.append((f"{child}.{fk}", f"{parent}.{pk}", orphans, childless, max_children))

report += ["## 4. Relationships", ""]
report += [
    "Counts are in distinct key values. *Child keys without parent* = orphans. "
    "*Parents without child* = parent keys that no child row refers to.",
    "",
]
report += md_table(
    ["child (foreign key)", "parent (key)", "child keys without parent", "parents without child", "max children per parent"],
    rel_rows,
)


# %% [markdown]
# ## 5. Early checks on the known traps
#
# Only counting here. What to DO about each issue is decided in Phase 1 (docs/decision_log.md).

# %%
TRAP_CHECKS = [
    (
        "customers: rows (one customer_id per order)",
        "SELECT count(*) FROM raw.customers",
    ),
    (
        "customers: distinct customer_unique_id (real people)",
        "SELECT count(DISTINCT customer_unique_id) FROM raw.customers",
    ),
    (
        "customers: customer_unique_id with more than one customer_id (repeat buyers, before any filter)",
        "SELECT count(*) FROM (SELECT customer_unique_id FROM raw.customers GROUP BY 1 HAVING count(*) > 1)",
    ),
    (
        "orders: status = 'delivered'",
        "SELECT count(*) FROM raw.orders WHERE order_status = 'delivered'",
    ),
    (
        "orders: status = 'delivered' but customer delivery date is missing",
        "SELECT count(*) FROM raw.orders WHERE order_status = 'delivered' AND order_delivered_customer_date IS NULL",
    ),
    (
        "orders: status is NOT 'delivered' but a customer delivery date exists",
        "SELECT count(*) FROM raw.orders WHERE order_status <> 'delivered' AND order_delivered_customer_date IS NOT NULL",
    ),
    (
        "order items: orders with more than one item row",
        "SELECT count(*) FROM (SELECT order_id FROM raw.order_items GROUP BY 1 HAVING count(*) > 1)",
    ),
    (
        "order items: orders with items from more than one seller",
        "SELECT count(*) FROM (SELECT order_id FROM raw.order_items GROUP BY 1 HAVING count(DISTINCT seller_id) > 1)",
    ),
    (
        "order items: rows with shipping_limit_date after 2018-12-31",
        "SELECT count(*) FROM raw.order_items WHERE shipping_limit_date > TIMESTAMP '2018-12-31 23:59:59'",
    ),
    (
        "payments: rows with 0 instalments",
        "SELECT count(*) FROM raw.order_payments WHERE payment_installments = 0",
    ),
    (
        "payments: rows with payment_value = 0",
        "SELECT count(*) FROM raw.order_payments WHERE payment_value = 0",
    ),
    (
        "reviews: review_id values that appear on more than one row",
        "SELECT count(*) FROM (SELECT review_id FROM raw.order_reviews GROUP BY 1 HAVING count(*) > 1)",
    ),
    (
        "reviews: review_id values linked to more than one order",
        "SELECT count(*) FROM (SELECT review_id FROM raw.order_reviews GROUP BY 1 HAVING count(DISTINCT order_id) > 1)",
    ),
    (
        "reviews: orders with more than one review",
        "SELECT count(*) FROM (SELECT order_id FROM raw.order_reviews GROUP BY 1 HAVING count(*) > 1)",
    ),
    (
        "reviews: rows with a written comment message",
        "SELECT count(*) FROM raw.order_reviews WHERE trim(review_comment_message) <> ''",
    ),
    (
        "reviews: rows with score 1-2",
        "SELECT count(*) FROM raw.order_reviews WHERE review_score <= 2",
    ),
    (
        "reviews: rows with score 1-2 AND a written comment message (sampling frame for Phase 5)",
        "SELECT count(*) FROM raw.order_reviews WHERE review_score <= 2 AND trim(review_comment_message) <> ''",
    ),
    (
        "products: rows without a category",
        "SELECT count(*) FROM raw.products WHERE product_category_name IS NULL",
    ),
    (
        "products: rows where category, name length, description length and photos are ALL missing",
        """SELECT count(*) FROM raw.products
           WHERE product_category_name IS NULL AND product_name_lenght IS NULL
             AND product_description_lenght IS NULL AND product_photos_qty IS NULL""",
    ),
    (
        "products: rows with weight = 0",
        "SELECT count(*) FROM raw.products WHERE product_weight_g = 0",
    ),
    (
        "products: distinct categories without an English translation",
        """SELECT count(DISTINCT p.product_category_name) FROM raw.products p
           WHERE p.product_category_name IS NOT NULL AND NOT EXISTS (
               SELECT 1 FROM raw.category_translation t WHERE t.product_category_name = p.product_category_name)""",
    ),
    (
        "geolocation: rows",
        "SELECT count(*) FROM raw.geolocation",
    ),
    (
        "geolocation: rows that are exact duplicates of another row",
        "SELECT (SELECT count(*) FROM raw.geolocation) - (SELECT count(*) FROM (SELECT DISTINCT * FROM raw.geolocation))",
    ),
    (
        "geolocation: distinct zip code prefixes",
        "SELECT count(DISTINCT geolocation_zip_code_prefix) FROM raw.geolocation",
    ),
    (
        "geolocation: zip code prefixes mapped to more than one state",
        """SELECT count(*) FROM (SELECT geolocation_zip_code_prefix FROM raw.geolocation
           GROUP BY 1 HAVING count(DISTINCT geolocation_state) > 1)""",
    ),
    (
        "geolocation: rows outside a rough bounding box of Brazil (lat -34 to 6, lng -74 to -34)",
        """SELECT count(*) FROM raw.geolocation
           WHERE geolocation_lat NOT BETWEEN -34 AND 6 OR geolocation_lng NOT BETWEEN -74 AND -34""",
    ),
]

trap_rows = [(label, scalar(sql)) for label, sql in TRAP_CHECKS]

status_rows = con.execute(
    """
    SELECT order_status,
           count(*) AS orders,
           count(order_delivered_customer_date) AS with_customer_delivery_date
    FROM raw.orders
    GROUP BY order_status
    ORDER BY orders DESC
    """
).fetchall()

no_item_rows = con.execute(
    """
    SELECT o.order_status, count(*) AS orders
    FROM raw.orders o
    WHERE NOT EXISTS (SELECT 1 FROM raw.order_items i WHERE i.order_id = o.order_id)
    GROUP BY o.order_status
    ORDER BY orders DESC
    """
).fetchall()

payment_type_rows = con.execute(
    "SELECT payment_type, count(*) AS payment_rows FROM raw.order_payments GROUP BY 1 ORDER BY 2 DESC"
).fetchall()

untranslated = con.execute(
    """
    SELECT DISTINCT p.product_category_name
    FROM raw.products p
    WHERE p.product_category_name IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM raw.category_translation t
                      WHERE t.product_category_name = p.product_category_name)
    ORDER BY 1
    """
).fetchall()

score_rows = con.execute(
    """
    SELECT review_score,
           count(*) AS reviews,
           count(*) FILTER (WHERE trim(review_comment_message) <> '') AS with_comment_message
    FROM raw.order_reviews
    GROUP BY review_score
    ORDER BY review_score
    """
).fetchall()

report += ["## 5. Early checks on the known traps", ""]
report += md_table(["check", "count"], trap_rows)
report += ["### Orders by status", ""]
report += md_table(["order_status", "orders", "with customer delivery date"], status_rows)
report += ["### Orders without any item row, by status", ""]
report += md_table(["order_status", "orders"], no_item_rows)
report += ["### Payment rows by type", ""]
report += md_table(["payment_type", "payment rows"], payment_type_rows)
report += ["### Reviews by score", ""]
report += md_table(["review_score", "reviews", "with comment message"], score_rows)
report += ["### Categories without an English translation", ""]
report += [", ".join(f"`{row[0]}`" for row in untranslated) or "none", ""]


# %% [markdown]
# ## 6. Orders per purchase month
#
# The min/max dates above only show the first and the last order. This table shows whether
# every month in between is complete - important before drawing any monthly trend.

# %%
month_rows = con.execute(
    """
    SELECT strftime(date_trunc('month', order_purchase_timestamp), '%Y-%m') AS purchase_month,
           count(*) AS orders,
           count(*) FILTER (WHERE order_status = 'delivered') AS delivered_orders
    FROM raw.orders
    GROUP BY 1
    ORDER BY 1
    """
).fetchall()

report += ["## 6. Orders per purchase month", ""]
report += md_table(["purchase month", "orders", "delivered orders"], month_rows)


# %% [markdown]
# ## Write the report

# %%
REPORT_PATH.write_text("\n".join(report), encoding="utf-8")
con.close()
print("\n".join(report))
print(f"\nReport written to {REPORT_PATH.relative_to(ROOT)}")
