# %% [markdown]
# # 01 - Data quality checks (Phase 1)
#
# Goal: measure every data quality issue that could distort the analysis, so that each
# cleaning decision in docs/decision_log.md is backed by a row count.
#
# Input : data/processed/olist.duckdb (built by `python run_sql.py`)
# Output: docs/data_quality_report.md (generated - do not edit by hand)
#
# This script only READS the data. Nothing is deleted or changed here: the decisions are
# applied later, in the model layer (Phase 2), where they are visible in the SQL.

# %%
import sys
from pathlib import Path

import duckdb

# Windows consoles default to a legacy code page; force UTF-8 so Portuguese text prints safely.
sys.stdout.reconfigure(encoding="utf-8")

try:
    ROOT = Path(__file__).resolve().parents[1]
except NameError:  # running cell by cell: fall back to the working directory
    ROOT = Path.cwd() if (Path.cwd() / "sql").exists() else Path.cwd().parent

DB_PATH = ROOT / "data" / "processed" / "olist.duckdb"
REPORT_PATH = ROOT / "docs" / "data_quality_report.md"

con = duckdb.connect(str(DB_PATH), read_only=True)
report = []  # lines of the markdown report


# %%
def fmt(value) -> str:
    """Format a value for a markdown table cell."""
    if value is None:
        return ""
    if isinstance(value, int):
        return f"{value:,}"
    if isinstance(value, float):
        return f"{value:,.2f}"
    return str(value).replace("\r", " ").replace("\n", " ").replace("|", "/")


def md_table(headers, rows) -> list:
    """Build a markdown table from a header list and a list of rows."""
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(fmt(v) for v in row) + " |" for row in rows]
    return lines + [""]


def scalar(sql: str):
    """Run a query that returns one single value."""
    return con.execute(sql).fetchone()[0]


def rows(sql: str) -> list:
    """Run a query and return all rows."""
    return con.execute(sql).fetchall()


def count_table(checks) -> list:
    """Turn a list of (id, description, sql) checks into a markdown table of counts."""
    return md_table(["id", "check", "count"], [(cid, label, scalar(sql)) for cid, label, sql in checks])


# Two helper views used by several checks (temporary: they live only in this session).
#
# v_delivered: orders that really reached the customer (status delivered AND a delivery date).
#   delivery_days = calendar days from purchase to delivery
#   delay_days    = calendar days between the promised date and the delivery (positive = late)
# v_review_latest: at most one review per order - the most recently answered one.
con.execute(
    """
    CREATE TEMP VIEW v_delivered AS
    SELECT o.*,
           date_diff('day', o.order_purchase_timestamp::DATE, o.order_delivered_customer_date::DATE) AS delivery_days,
           date_diff('day', o.order_estimated_delivery_date::DATE, o.order_delivered_customer_date::DATE) AS delay_days
    FROM raw.orders o
    WHERE o.order_status = 'delivered' AND o.order_delivered_customer_date IS NOT NULL
    """
)
con.execute(
    """
    CREATE TEMP VIEW v_review_latest AS
    SELECT * EXCLUDE (rn)
    FROM (
        SELECT r.*,
               row_number() OVER (PARTITION BY order_id
                                  ORDER BY review_answer_timestamp DESC, review_id DESC) AS rn
        FROM raw.order_reviews r
    )
    WHERE rn = 1
    """
)

report += [
    "# Data quality report",
    "",
    "Generated by `notebooks/01_data_quality_checks.py` from `data/processed/olist.duckdb` "
    f"(DuckDB {duckdb.__version__}). Do not edit by hand: re-run the script instead.",
    "",
    "Duplicate keys and orphan records were already tested in `docs/profiling_report.md` "
    "(sections 3 and 4): no duplicate primary keys, no orphan items, payments or reviews.",
    "",
]


# %% [markdown]
# ## A. Scope: which orders can be analysed at all?

# %%
report += ["## A. Scope: order status and analysis period", ""]
report += count_table(
    [
        ("A1", "orders in total", "SELECT count(*) FROM raw.orders"),
        ("A2", "orders with status other than 'delivered'",
         "SELECT count(*) FROM raw.orders WHERE order_status <> 'delivered'"),
        ("A3", "orders purchased before 2017-01-01 (incomplete months)",
         "SELECT count(*) FROM raw.orders WHERE order_purchase_timestamp < TIMESTAMP '2017-01-01'"),
        ("A4", "orders purchased from 2018-09-01 (incomplete months)",
         "SELECT count(*) FROM raw.orders WHERE order_purchase_timestamp >= TIMESTAMP '2018-09-01'"),
        ("A5", "orders purchased 2017-01-01 to 2018-08-31 (analysis period)",
         """SELECT count(*) FROM raw.orders
            WHERE order_purchase_timestamp >= TIMESTAMP '2017-01-01'
              AND order_purchase_timestamp <  TIMESTAMP '2018-09-01'"""),
        ("A6", "delivered orders with a delivery date, inside the analysis period",
         """SELECT count(*) FROM v_delivered
            WHERE order_purchase_timestamp >= TIMESTAMP '2017-01-01'
              AND order_purchase_timestamp <  TIMESTAMP '2018-09-01'"""),
        ("A7", "delivered orders with a delivery date (all periods)", "SELECT count(*) FROM v_delivered"),
        ("A8", "orders whose (latest) review has 1-2 stars",
         "SELECT count(*) FROM v_review_latest WHERE review_score <= 2"),
        ("A9", "of these: the order status is not 'delivered'",
         """SELECT count(*) FROM v_review_latest r JOIN raw.orders o USING (order_id)
            WHERE r.review_score <= 2 AND o.order_status <> 'delivered'"""),
    ]
)

report += ["### Review outcome by order status (one review per order: the latest)", ""]
report += md_table(
    ["order_status", "orders", "orders with review", "reviews with 1-2 stars", "share of 1-2 stars"],
    rows(
        """
        SELECT o.order_status,
               count(*) AS orders,
               count(r.order_id) AS with_review,
               count(*) FILTER (WHERE r.review_score <= 2) AS low_reviews,
               printf('%.1f%%', 100.0 * count(*) FILTER (WHERE r.review_score <= 2) / nullif(count(r.order_id), 0))
        FROM raw.orders o
        LEFT JOIN v_review_latest r USING (order_id)
        GROUP BY o.order_status
        ORDER BY orders DESC
        """
    ),
)


# %% [markdown]
# ## B. Timestamps: are the dates logically possible?

# %%
report += ["## B. Timestamps", ""]
report += count_table(
    [
        ("B1", "status 'delivered' but customer delivery date missing",
         "SELECT count(*) FROM raw.orders WHERE order_status = 'delivered' AND order_delivered_customer_date IS NULL"),
        ("B2", "status not 'delivered' but customer delivery date present",
         "SELECT count(*) FROM raw.orders WHERE order_status <> 'delivered' AND order_delivered_customer_date IS NOT NULL"),
        ("B3", "delivered to customer BEFORE purchase",
         "SELECT count(*) FROM raw.orders WHERE order_delivered_customer_date < order_purchase_timestamp"),
        ("B4", "delivered to customer BEFORE handover to carrier",
         "SELECT count(*) FROM raw.orders WHERE order_delivered_customer_date < order_delivered_carrier_date"),
        ("B5", "handed to carrier BEFORE purchase",
         "SELECT count(*) FROM raw.orders WHERE order_delivered_carrier_date < order_purchase_timestamp"),
        ("B6", "handed to carrier BEFORE payment approval",
         "SELECT count(*) FROM raw.orders WHERE order_delivered_carrier_date < order_approved_at"),
        ("B7", "payment approved BEFORE purchase",
         "SELECT count(*) FROM raw.orders WHERE order_approved_at < order_purchase_timestamp"),
        ("B8", "estimated delivery date BEFORE purchase date",
         "SELECT count(*) FROM raw.orders WHERE order_estimated_delivery_date::DATE < order_purchase_timestamp::DATE"),
        ("B9", "delivered orders without payment approval date",
         "SELECT count(*) FROM v_delivered WHERE order_approved_at IS NULL"),
        ("B10", "delivered orders without carrier handover date",
         "SELECT count(*) FROM v_delivered WHERE order_delivered_carrier_date IS NULL"),
        ("B11", "delivered orders: delivered on the same calendar day as the estimated date",
         "SELECT count(*) FROM v_delivered WHERE delay_days = 0"),
        ("B12", "delivered orders: late by calendar day (delay_days > 0)",
         "SELECT count(*) FROM v_delivered WHERE delay_days > 0"),
        ("B13", "delivered orders: late by timestamp (delivery timestamp > estimated date at 00:00)",
         "SELECT count(*) FROM v_delivered WHERE order_delivered_customer_date > order_estimated_delivery_date"),
        ("B14", "delivered orders: delivery took more than 60 days",
         "SELECT count(*) FROM v_delivered WHERE delivery_days > 60"),
        ("B15", "delivered orders: more than 30 days late",
         "SELECT count(*) FROM v_delivered WHERE delay_days > 30"),
    ]
)

report += ["### Distribution of delivery time and delay (delivered orders, calendar days)", ""]
report += md_table(
    ["measure", "min", "p1", "p25", "median", "p75", "p95", "p99", "max"],
    rows(
        """
        SELECT 'delivery_days (purchase to delivery)',
               min(delivery_days), quantile_cont(delivery_days, 0.01), quantile_cont(delivery_days, 0.25),
               quantile_cont(delivery_days, 0.50), quantile_cont(delivery_days, 0.75),
               quantile_cont(delivery_days, 0.95), quantile_cont(delivery_days, 0.99), max(delivery_days)
        FROM v_delivered
        UNION ALL
        SELECT 'delay_days (positive = late)',
               min(delay_days), quantile_cont(delay_days, 0.01), quantile_cont(delay_days, 0.25),
               quantile_cont(delay_days, 0.50), quantile_cont(delay_days, 0.75),
               quantile_cont(delay_days, 0.95), quantile_cont(delay_days, 0.99), max(delay_days)
        FROM v_delivered
        """
    ),
)


# %% [markdown]
# ## C. Prices, freight and payments: extreme or inconsistent values

# %%
report += ["## C. Price, freight and payment values", ""]
report += count_table(
    [
        ("C1", "item rows with price <= 0", "SELECT count(*) FROM raw.order_items WHERE price <= 0"),
        ("C2", "item rows with freight = 0", "SELECT count(*) FROM raw.order_items WHERE freight_value = 0"),
        ("C3", "item rows where freight is higher than the price",
         "SELECT count(*) FROM raw.order_items WHERE freight_value > price"),
        ("C4", "item rows with price above 2,000 BRL", "SELECT count(*) FROM raw.order_items WHERE price > 2000"),
        ("C5", "orders with both items and payments",
         """SELECT count(*) FROM (SELECT DISTINCT order_id FROM raw.order_items) i
            JOIN (SELECT DISTINCT order_id FROM raw.order_payments) p USING (order_id)"""),
        ("C6", "of these: items total (price + freight) differs from payments total by more than 0.01 BRL",
         """SELECT count(*) FROM
              (SELECT order_id, sum(price + freight_value) AS items_total FROM raw.order_items GROUP BY 1) i
            JOIN (SELECT order_id, sum(payment_value) AS paid_total FROM raw.order_payments GROUP BY 1) p USING (order_id)
            WHERE abs(items_total - paid_total) > 0.01"""),
        ("C7", "of these: difference of more than 1.00 BRL",
         """SELECT count(*) FROM
              (SELECT order_id, sum(price + freight_value) AS items_total FROM raw.order_items GROUP BY 1) i
            JOIN (SELECT order_id, sum(payment_value) AS paid_total FROM raw.order_payments GROUP BY 1) p USING (order_id)
            WHERE abs(items_total - paid_total) > 1.00"""),
        ("C8", "payment rows with value = 0", "SELECT count(*) FROM raw.order_payments WHERE payment_value = 0"),
        ("C9", "payment rows with type 'not_defined'",
         "SELECT count(*) FROM raw.order_payments WHERE payment_type = 'not_defined'"),
    ]
)

report += ["### Distribution of item price and freight (BRL, all item rows)", ""]
report += md_table(
    ["measure", "min", "p25", "median", "mean", "p75", "p95", "p99", "p99.9", "max"],
    rows(
        """
        SELECT 'price', min(price)::DOUBLE, quantile_cont(price::DOUBLE, 0.25), quantile_cont(price::DOUBLE, 0.50),
               avg(price), quantile_cont(price::DOUBLE, 0.75), quantile_cont(price::DOUBLE, 0.95),
               quantile_cont(price::DOUBLE, 0.99), quantile_cont(price::DOUBLE, 0.999), max(price)::DOUBLE
        FROM raw.order_items
        UNION ALL
        SELECT 'freight_value', min(freight_value)::DOUBLE, quantile_cont(freight_value::DOUBLE, 0.25),
               quantile_cont(freight_value::DOUBLE, 0.50), avg(freight_value),
               quantile_cont(freight_value::DOUBLE, 0.75), quantile_cont(freight_value::DOUBLE, 0.95),
               quantile_cont(freight_value::DOUBLE, 0.99), quantile_cont(freight_value::DOUBLE, 0.999),
               max(freight_value)::DOUBLE
        FROM raw.order_items
        """
    ),
)

report += ["### The 5 most expensive item rows (plausibility check)", ""]
report += md_table(
    ["price", "freight_value", "category", "order_status"],
    rows(
        """
        SELECT i.price::DOUBLE, i.freight_value::DOUBLE, coalesce(p.product_category_name, '(no category)'), o.order_status
        FROM raw.order_items i
        JOIN raw.products p USING (product_id)
        JOIN raw.orders o USING (order_id)
        ORDER BY i.price DESC
        LIMIT 5
        """
    ),
)

report += ["### The 5 highest freight values (plausibility check)", ""]
report += md_table(
    ["freight_value", "price", "category", "product_weight_g"],
    rows(
        """
        SELECT i.freight_value::DOUBLE, i.price::DOUBLE, coalesce(p.product_category_name, '(no category)'), p.product_weight_g
        FROM raw.order_items i
        JOIN raw.products p USING (product_id)
        ORDER BY i.freight_value DESC
        LIMIT 5
        """
    ),
)


# %% [markdown]
# ## D. Reviews: duplicates, missing reviews and timing

# %%
report += ["## D. Reviews", ""]
report += count_table(
    [
        ("D1", "review rows", "SELECT count(*) FROM raw.order_reviews"),
        ("D2", "orders with at least one review", "SELECT count(DISTINCT order_id) FROM raw.order_reviews"),
        ("D3", "orders with more than one review",
         "SELECT count(*) FROM (SELECT order_id FROM raw.order_reviews GROUP BY 1 HAVING count(*) > 1)"),
        ("D4", "of these: the reviews have different scores",
         """SELECT count(*) FROM (SELECT order_id FROM raw.order_reviews GROUP BY 1
            HAVING count(*) > 1 AND count(DISTINCT review_score) > 1)"""),
        ("D5", "review rows removed by keeping only the latest review per order",
         "SELECT (SELECT count(*) FROM raw.order_reviews) - (SELECT count(*) FROM v_review_latest)"),
        ("D6", "review_id values linked to more than one order",
         "SELECT count(*) FROM (SELECT review_id FROM raw.order_reviews GROUP BY 1 HAVING count(DISTINCT order_id) > 1)"),
        ("D7", "review rows that belong to such a shared review_id",
         """SELECT count(*) FROM raw.order_reviews WHERE review_id IN
            (SELECT review_id FROM raw.order_reviews GROUP BY 1 HAVING count(DISTINCT order_id) > 1)"""),
        ("D8", "shared review_id values whose rows differ in score or comment",
         """SELECT count(*) FROM (SELECT review_id FROM raw.order_reviews GROUP BY 1
            HAVING count(DISTINCT order_id) > 1
               AND (count(DISTINCT review_score) > 1
                    OR count(DISTINCT coalesce(review_comment_message, '')) > 1))"""),
        ("D9", "shared review_id values whose orders belong to different people (customer_unique_id)",
         """SELECT count(*) FROM (
              SELECT r.review_id
              FROM raw.order_reviews r
              JOIN raw.orders o USING (order_id)
              JOIN raw.customers c USING (customer_id)
              GROUP BY 1
              HAVING count(DISTINCT r.order_id) > 1 AND count(DISTINCT c.customer_unique_id) > 1)"""),
        ("D10", "review rows whose comment message contains only spaces",
         "SELECT count(*) FROM raw.order_reviews WHERE review_comment_message IS NOT NULL AND trim(review_comment_message) = ''"),
        ("D11", "orders without any review",
         "SELECT count(*) FROM raw.orders o WHERE NOT EXISTS (SELECT 1 FROM raw.order_reviews r WHERE r.order_id = o.order_id)"),
        ("D12", "delivered orders whose (latest) review was answered BEFORE the delivery",
         """SELECT count(*) FROM v_delivered d JOIN v_review_latest r USING (order_id)
            WHERE r.review_answer_timestamp < d.order_delivered_customer_date"""),
        ("D13", "1-2 star reviews with a written comment, distinct review_id (sampling frame without repeats)",
         """SELECT count(DISTINCT review_id) FROM raw.order_reviews
            WHERE review_score <= 2 AND trim(review_comment_message) <> ''"""),
    ]
)

# When is the satisfaction survey sent? (review_creation_date = the day the survey was sent)
report += ["### Survey timing: when is the survey sent to the customer?", ""]
report += count_table(
    [
        ("D14", "on-time delivered orders with a review",
         "SELECT count(*) FROM v_delivered d JOIN v_review_latest r USING (order_id) WHERE d.delay_days <= 0"),
        ("D15", "of these: survey sent 0-1 calendar days after the delivery",
         """SELECT count(*) FROM v_delivered d JOIN v_review_latest r USING (order_id)
            WHERE d.delay_days <= 0
              AND date_diff('day', d.order_delivered_customer_date::DATE, r.review_creation_date::DATE) BETWEEN 0 AND 1"""),
        ("D16", "late delivered orders with a review",
         "SELECT count(*) FROM v_delivered d JOIN v_review_latest r USING (order_id) WHERE d.delay_days > 0"),
        ("D17", "of these: survey sent 0-3 calendar days after the ESTIMATED delivery date",
         """SELECT count(*) FROM v_delivered d JOIN v_review_latest r USING (order_id)
            WHERE d.delay_days > 0
              AND date_diff('day', d.order_estimated_delivery_date::DATE, r.review_creation_date::DATE) BETWEEN 0 AND 3"""),
        ("D18", "of these: survey sent BEFORE the order was delivered",
         """SELECT count(*) FROM v_delivered d JOIN v_review_latest r USING (order_id)
            WHERE d.delay_days > 0 AND r.review_creation_date::DATE < d.order_delivered_customer_date::DATE"""),
    ]
)

report += ["### Missing reviews and early reviews: delivered orders, on time vs late", ""]
report += md_table(
    ["delivery outcome", "delivered orders", "without review", "share without review",
     "review answered before delivery", "share answered before delivery"],
    rows(
        """
        SELECT CASE WHEN d.delay_days > 0 THEN 'late' ELSE 'on time' END AS outcome,
               count(*) AS orders,
               count(*) FILTER (WHERE r.order_id IS NULL) AS no_review,
               printf('%.2f%%', 100.0 * count(*) FILTER (WHERE r.order_id IS NULL) / count(*)),
               count(*) FILTER (WHERE r.review_answer_timestamp < d.order_delivered_customer_date) AS early,
               printf('%.2f%%', 100.0 * count(*) FILTER (WHERE r.review_answer_timestamp < d.order_delivered_customer_date)
                                / count(r.order_id))
        FROM v_delivered d
        LEFT JOIN v_review_latest r USING (order_id)
        GROUP BY 1
        ORDER BY 1 DESC
        """
    ),
)

report += ["### Orders without a review, by order status", ""]
report += md_table(
    ["order_status", "orders", "without review", "share without review"],
    rows(
        """
        SELECT o.order_status, count(*) AS orders,
               count(*) FILTER (WHERE r.order_id IS NULL) AS no_review,
               printf('%.2f%%', 100.0 * count(*) FILTER (WHERE r.order_id IS NULL) / count(*))
        FROM raw.orders o
        LEFT JOIN v_review_latest r USING (order_id)
        GROUP BY 1
        ORDER BY orders DESC
        """
    ),
)


# %% [markdown]
# ## E. Products, sellers, customers and geography

# %%
report += ["## E. Products, sellers, customers, geography", ""]
report += count_table(
    [
        ("E1", "item rows in total", "SELECT count(*) FROM raw.order_items"),
        ("E2", "item rows whose product has no category",
         """SELECT count(*) FROM raw.order_items i JOIN raw.products p USING (product_id)
            WHERE p.product_category_name IS NULL"""),
        ("E3", "item rows whose category has no English translation",
         """SELECT count(*) FROM raw.order_items i JOIN raw.products p USING (product_id)
            WHERE p.product_category_name IS NOT NULL AND NOT EXISTS
              (SELECT 1 FROM raw.category_translation t WHERE t.product_category_name = p.product_category_name)"""),
        ("E4", "orders with items from more than one seller",
         "SELECT count(*) FROM (SELECT order_id FROM raw.order_items GROUP BY 1 HAVING count(DISTINCT seller_id) > 1)"),
        ("E5", "orders with items from more than one product category",
         """SELECT count(*) FROM (
              SELECT i.order_id FROM raw.order_items i JOIN raw.products p USING (product_id)
              GROUP BY 1 HAVING count(DISTINCT coalesce(p.product_category_name, '(no category)')) > 1)"""),
        ("E6", "people (customer_unique_id) with orders delivered to more than one state",
         "SELECT count(*) FROM (SELECT customer_unique_id FROM raw.customers GROUP BY 1 HAVING count(DISTINCT customer_state) > 1)"),
        ("E7", "customer rows whose zip prefix is missing in geolocation",
         """SELECT count(*) FROM raw.customers c WHERE NOT EXISTS
              (SELECT 1 FROM raw.geolocation g WHERE g.geolocation_zip_code_prefix = c.customer_zip_code_prefix)"""),
        ("E8", "sellers whose zip prefix is missing in geolocation",
         """SELECT count(*) FROM raw.sellers s WHERE NOT EXISTS
              (SELECT 1 FROM raw.geolocation g WHERE g.geolocation_zip_code_prefix = s.seller_zip_code_prefix)"""),
        ("E9", "customer rows with a missing or empty state",
         "SELECT count(*) FROM raw.customers WHERE customer_state IS NULL OR trim(customer_state) = ''"),
        ("E10", "sellers with a missing or empty state",
         "SELECT count(*) FROM raw.sellers WHERE seller_state IS NULL OR trim(seller_state) = ''"),
    ]
)

report += ["### Share of item value (sum of price) without a usable category", ""]
report += md_table(
    ["group", "item rows", "sum of price (BRL)", "share of total price"],
    rows(
        """
        WITH x AS (
            SELECT CASE WHEN p.product_category_name IS NULL THEN 'no category'
                        WHEN t.product_category_name IS NULL THEN 'category without translation'
                        ELSE 'category with translation' END AS grp,
                   i.price
            FROM raw.order_items i
            JOIN raw.products p USING (product_id)
            LEFT JOIN raw.category_translation t ON t.product_category_name = p.product_category_name
        )
        SELECT grp, count(*), sum(price)::DOUBLE, printf('%.2f%%', 100.0 * sum(price) / (SELECT sum(price) FROM x))
        FROM x GROUP BY 1 ORDER BY 2 DESC
        """
    ),
)


# %% [markdown]
# ## Write the report

# %%
REPORT_PATH.write_text("\n".join(report), encoding="utf-8")
con.close()
print("\n".join(report))
print(f"\nReport written to {REPORT_PATH.relative_to(ROOT)}")
