# %% [markdown]
# # 03 - KPI baseline (Phase 3)
#
# Goal: print the official value of every KPI, with its numerator and denominator.
# These are the reference numbers: the Power BI measures and every figure in the deck must match them.
#
# Input : data/processed/olist.duckdb, views model.kpi_orders and model.kpi_customers (sql/05_kpis.sql)
# Output: docs/kpi_baseline.md (generated - do not edit by hand)

# %%
import sys
from pathlib import Path

import duckdb

# Windows consoles default to a legacy code page; force UTF-8 so the report prints safely.
sys.stdout.reconfigure(encoding="utf-8")

try:
    ROOT = Path(__file__).resolve().parents[1]
except NameError:  # running cell by cell: fall back to the working directory
    ROOT = Path.cwd() if (Path.cwd() / "sql").exists() else Path.cwd().parent

DB_PATH = ROOT / "data" / "processed" / "olist.duckdb"
REPORT_PATH = ROOT / "docs" / "kpi_baseline.md"

con = duckdb.connect(str(DB_PATH), read_only=True)


# %%
def md_table(headers, rows) -> list:
    """Build a markdown table from a header list and a list of already formatted rows."""
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(str(v) for v in row) + " |" for row in rows]
    return lines + [""]


def as_dict(sql: str) -> dict:
    """Run a query that returns one row and give it back as {column name: value}."""
    cursor = con.execute(sql)
    names = [col[0] for col in cursor.description]
    return dict(zip(names, cursor.fetchone()))


def n(value) -> str:      # whole number with thousands separator
    return f"{value:,.0f}"


def money(value) -> str:  # BRL with two decimals
    return f"{value:,.2f}"


def pct(value) -> str:    # rate as a percentage with two decimals
    return f"{value:.2%}"


def dec(value) -> str:    # plain number with two decimals
    return f"{value:.2f}"


# %% [markdown]
# ## 1. Whole analysis period

# %%
k = as_dict("SELECT * FROM model.kpi_orders WHERE period = 'Total'")
c = as_dict("SELECT * FROM model.kpi_customers")

kpi_rows = [
    ("Number of orders", n(k["orders"]), "", ""),
    ("GMV (BRL)", money(k["gmv"]), "", ""),
    ("Average order value (BRL)", money(k["avg_order_value"]), money(k["gmv"]), n(k["orders_with_items"])),
    ("Freight share of order value", pct(k["freight_share"]), money(k["freight_total"]),
     money(k["gmv"] + k["freight_total"])),
    ("On-time delivery rate", pct(k["on_time_rate"]), n(k["on_time_orders"]), n(k["delivered_orders"])),
    ("Late delivery rate", pct(k["late_rate"]), n(k["late_orders"]), n(k["delivered_orders"])),
    ("Not-delivered rate", pct(k["not_delivered_rate"]), n(k["not_delivered_orders"]), n(k["orders"])),
    ("Average delay, late orders only (days)", dec(k["avg_delay_days_late"]), "", n(k["late_orders"])),
    ("Median delay, late orders only (days)", dec(k["median_delay_days_late"]), "", n(k["late_orders"])),
    ("Average delivery time (days)", dec(k["avg_delivery_days"]), "", n(k["delivered_orders"])),
    ("Median delivery time (days)", dec(k["median_delivery_days"]), "", n(k["delivered_orders"])),
    ("Average review score", dec(k["avg_review_score"]), "", n(k["reviewed_orders"])),
    ("Share of 1-2 star reviews", pct(k["low_score_rate"]), n(k["low_score_orders"]), n(k["reviewed_orders"])),
    ("Share of reviews with a written comment", pct(k["comment_rate"]), n(k["commented_orders"]),
     n(k["reviewed_orders"])),
    ("Repeat purchase rate", pct(c["repeat_purchase_rate"]), n(c["repeat_customers"]), n(c["customers"])),
]

report = [
    "# KPI baseline",
    "",
    "Generated by `notebooks/03_kpi_baseline.py` from the views in `sql/05_kpis.sql` "
    f"(DuckDB {duckdb.__version__}). Do not edit by hand: re-run the script instead.",
    "",
    "Definitions: [`metric_definitions.md`](metric_definitions.md). "
    "Analysis period: orders purchased from 2017-01-01 to 2018-08-31.",
    "",
    "## 1. Whole analysis period",
    "",
    "For rates, *numerator / denominator = value*. For averages, the denominator column shows the number "
    "of orders the average is taken over.",
    "",
]
report += md_table(["KPI", "value", "numerator", "denominator"], kpi_rows)

# %% [markdown]
# ## 2. Supporting figures
# Not KPIs: figures that explain what is inside the KPIs (used in the caveats of the definitions).

# %%
s = as_dict(
    """
    SELECT
        sum(items_value) FILTER (WHERE delivery_outcome = 'Not delivered')  AS gmv_not_delivered,
        count(*) FILTER (WHERE delivery_outcome = 'Not delivered' AND has_items) AS not_delivered_with_items,
        sum(items_value)                                                     AS gmv,
        count(*) FILTER (WHERE NOT has_items)                                AS orders_without_items,
        count(*) FILTER (WHERE NOT has_review)                               AS orders_without_review,
        count(*) FILTER (WHERE delivery_outcome = 'Unknown')                 AS unknown_outcome,
        median(items_value)                                                  AS median_order_value,
        median(delay_days)                                                   AS median_delay_all_delivered
    FROM model.fact_orders
    """
)
r = as_dict(
    """
    SELECT count(*) FILTER (WHERE order_count > 1) AS multi_order_customers,
           count(*) FILTER (WHERE order_count > 1) / count(*) AS multi_order_rate
    FROM model.dim_customer
    """
)

report += ["## 2. Supporting figures", ""]
report += md_table(
    ["figure", "value"],
    [
        ("Orders without item rows (no value, excluded from GMV and average order value)", n(s["orders_without_items"])),
        ("Not-delivered orders that have item rows (included in GMV)", n(s["not_delivered_with_items"])),
        ("GMV of not-delivered orders (BRL)", money(s["gmv_not_delivered"])),
        ("GMV of not-delivered orders as a share of GMV", pct(s["gmv_not_delivered"] / s["gmv"])),
        ("Median order value (BRL)", money(s["median_order_value"])),
        ("Median delay of all delivered orders in days (negative = before the promised date)",
         dec(s["median_delay_all_delivered"])),
        ("Orders without a review (excluded from satisfaction KPIs)", n(s["orders_without_review"])),
        ("Delivered orders without a delivery date (excluded from delivery KPIs)", n(s["unknown_outcome"])),
        ("Customers with more than one order, including same-day orders", n(r["multi_order_customers"])),
        ("Repeat purchase rate if same-day orders were counted as repeats", pct(r["multi_order_rate"])),
    ],
)

report += ["### Review score distribution (one review per order)", ""]
report += md_table(
    ["review score", "orders", "share of reviewed orders"],
    [
        (row[0], n(row[1]), pct(row[2]))
        for row in con.execute(
            """
            SELECT review_score, count(*), count(*) / sum(count(*)) OVER ()
            FROM model.fact_orders
            WHERE has_review
            GROUP BY review_score
            ORDER BY review_score
            """
        ).fetchall()
    ],
)

# %% [markdown]
# ## 3. KPIs by purchase month

# %%
monthly = con.execute(
    """
    SELECT period, orders, gmv, avg_order_value, freight_share, on_time_rate, late_rate, not_delivered_rate,
           avg_delay_days_late, median_delivery_days, avg_review_score, low_score_rate, comment_rate
    FROM model.kpi_orders
    WHERE period <> 'Total'
    ORDER BY period
    """
).fetchall()

report += ["## 3. KPIs by purchase month", ""]
report += md_table(
    ["month", "orders", "GMV (BRL)", "avg order value", "freight share", "on-time rate", "late rate",
     "not-delivered rate", "avg delay (late)", "median delivery days", "avg score", "1-2 star share",
     "comment share"],
    [
        (m[0], n(m[1]), money(m[2]), money(m[3]), pct(m[4]), pct(m[5]), pct(m[6]), pct(m[7]),
         dec(m[8]), dec(m[9]), dec(m[10]), pct(m[11]), pct(m[12]))
        for m in monthly
    ],
)

# %%
REPORT_PATH.write_text("\n".join(report), encoding="utf-8")
con.close()
print("\n".join(report))
print(f"\nReport written to {REPORT_PATH.relative_to(ROOT)}")
