# %% [markdown]
# # 08 - Reference values for the Power BI dashboard (Phase 7)
#
# Goal: give the dashboard builder the exact numbers each visual must show when no filter is applied.
# If a Power BI measure shows a different number, the DAX, a relationship or a data type is wrong.
#
# Input : data/processed/olist.duckdb (star schema), review_coding/coded_reviews.csv
# Output: dashboard/reference_values.md (generated - do not edit by hand)

# %%
import csv
import sys
from collections import Counter
from pathlib import Path

import duckdb

# Windows consoles default to a legacy code page; force UTF-8 so the report prints safely.
sys.stdout.reconfigure(encoding="utf-8")

try:
    ROOT = Path(__file__).resolve().parents[1]
except NameError:  # running cell by cell: fall back to the working directory
    ROOT = Path.cwd() if (Path.cwd() / "sql").exists() else Path.cwd().parent

con = duckdb.connect(str(ROOT / "data" / "processed" / "olist.duckdb"), read_only=True)
REPORT_PATH = ROOT / "dashboard" / "reference_values.md"


def md_table(headers, rows) -> list:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(str(v) for v in row) + " |" for row in rows]
    return lines + [""]


def one(sql: str):
    return con.execute(sql).fetchone()[0]


def n(v) -> str:
    return f"{v:,.0f}"


def pct(v) -> str:
    return f"{v:.1%}"


report = [
    "# Dashboard reference values",
    "",
    "Generated by `notebooks/08_dashboard_reference.py`. Do not edit by hand: re-run the script instead.",
    "",
    "Every value below is what the Power BI measure of the same name must show **with no filter applied**. "
    "Measure definitions: [`measures.dax`](measures.dax).",
    "",
]

# %% [markdown]
# ## 1. Measures on fact_orders (cards)

# %%
k = dict(zip(
    [c[0] for c in con.execute("SELECT * FROM model.kpi_orders WHERE period = 'Total'").description],
    con.execute("SELECT * FROM model.kpi_orders WHERE period = 'Total'").fetchone(),
))
c = con.execute("SELECT customers, repeat_customers, repeat_purchase_rate FROM model.kpi_customers").fetchone()
late_handover = one(
    "SELECT count(*) FILTER (WHERE is_seller_handover_late) / count(*) FROM model.fact_orders WHERE delivery_outcome = 'Late'"
)
report += ["## 1. Order measures (table `fact_orders`)", ""]
report += md_table(
    ["measure", "value"],
    [
        ("Orders", n(k["orders"])),
        ("Delivered Orders", n(k["delivered_orders"])),
        ("On-time Orders", n(k["on_time_orders"])),
        ("Late Orders", n(k["late_orders"])),
        ("Not Delivered Orders", n(k["not_delivered_orders"])),
        ("On-time Rate", f"{k['on_time_rate']:.2%}"),
        ("Late Rate", f"{k['late_rate']:.2%}"),
        ("Not-delivered Rate", f"{k['not_delivered_rate']:.2%}"),
        ("GMV", f"{k['gmv']:,.2f}"),
        ("Orders with Items", n(k["orders_with_items"])),
        ("Average Order Value", f"{k['avg_order_value']:,.2f}"),
        ("Freight Share", f"{k['freight_share']:.2%}"),
        ("Avg Delay (Late)", f"{k['avg_delay_days_late']:.2f}"),
        ("Median Delay (Late)", f"{k['median_delay_days_late']:.0f}"),
        ("Median Delivery Days", f"{k['median_delivery_days']:.0f}"),
        ("Reviewed Orders", n(k["reviewed_orders"])),
        ("Avg Review Score", f"{k['avg_review_score']:.2f}"),
        ("Low Score Orders", n(k["low_score_orders"])),
        ("Low Score Share", f"{k['low_score_rate']:.2%}"),
        ("Comment Share", f"{k['comment_rate']:.2%}"),
        ("Late Orders Handed Over Late by Seller (share)", f"{late_handover:.1%}"),
        ("Customers", n(c[0])),
        ("Repeat Customers", n(c[1])),
        ("Repeat Purchase Rate", f"{c[2]:.2%}"),
    ],
)

# %% [markdown]
# ## 2. Values behind each visual

# %%
report += ["## 2. Page 1: trend by month (axis `dim_date[year_month]`)", ""]
report += md_table(
    ["year_month", "Orders", "Late Rate", "Low Score Share", "Avg Review Score"],
    [(r[0], n(r[1]), pct(r[2]), pct(r[3]), f"{r[4]:.2f}") for r in con.execute(
        "SELECT period, orders, late_rate, low_score_rate, avg_review_score FROM model.kpi_orders "
        "WHERE period <> 'Total' ORDER BY period").fetchall()],
)

report += ["## 2b. Page 1: share of orders and of bad reviews by delivery outcome (axis `fact_orders[delivery_outcome]`)", ""]
report += md_table(
    ["delivery_outcome", "Orders", "Share of Orders", "Low Score Orders", "Share of Low Score Reviews"],
    [(r[0], n(r[1]), pct(r[2]), n(r[3]), pct(r[4])) for r in con.execute(
        """
        SELECT delivery_outcome, count(*), count(*) / sum(count(*)) OVER (),
               count(*) FILTER (WHERE is_low_score),
               count(*) FILTER (WHERE is_low_score) / sum(count(*) FILTER (WHERE is_low_score)) OVER ()
        FROM model.fact_orders GROUP BY delivery_outcome, delivery_outcome_sort ORDER BY delivery_outcome_sort
        """).fetchall()],
)

report += ["## 3. Page 2: by customer state (axis `dim_geography[state_name]`), top 10 by late rate", ""]
report += md_table(
    ["state_name", "Orders", "Late Orders", "Late Rate", "Low Score Share"],
    [(r[0], n(r[1]), n(r[2]), pct(r[3]), pct(r[4])) for r in con.execute(
        """
        SELECT g.state_name, count(*),
               count(*) FILTER (WHERE delivery_outcome = 'Late'),
               count(*) FILTER (WHERE delivery_outcome = 'Late') / count(*) FILTER (WHERE is_delivered),
               count(*) FILTER (WHERE is_low_score) / count(*) FILTER (WHERE has_review)
        FROM model.fact_orders f JOIN model.dim_geography g ON g.state_code = f.customer_state
        GROUP BY g.state_name
        HAVING count(*) >= 300
        ORDER BY 4 DESC LIMIT 10
        """).fetchall()],
)

report += ["## 4. Pages 2 and 3: by delay band (axis `fact_orders[delay_band]`)", ""]
report += md_table(
    ["delay_band", "Orders", "Low Score Share", "Avg Review Score"],
    [(r[0], n(r[1]), pct(r[2]), f"{r[3]:.2f}") for r in con.execute(
        """
        SELECT delay_band, count(*), count(*) FILTER (WHERE is_low_score) / count(*) FILTER (WHERE has_review),
               avg(review_score)
        FROM model.fact_orders GROUP BY delay_band, delay_band_sort ORDER BY delay_band_sort
        """).fetchall()],
)

report += ["## 5. Page 2: seller table (table `fact_order_items`, sellers with at least 30 orders), top 10 by late orders", ""]
report += md_table(
    ["seller_short", "seller_state", "Item Orders", "Item Late Orders", "Item Late Rate", "Item Low Score Share"],
    [(r[0], r[1], n(r[2]), n(r[3]), pct(r[4]), pct(r[5])) for r in con.execute(
        """
        SELECT left(i.seller_id, 8), s.seller_state,
               count(DISTINCT i.order_id),
               count(DISTINCT i.order_id) FILTER (WHERE i.delivery_outcome = 'Late'),
               count(DISTINCT i.order_id) FILTER (WHERE i.delivery_outcome = 'Late')
                   / count(DISTINCT i.order_id) FILTER (WHERE i.is_delivered),
               count(DISTINCT i.order_id) FILTER (WHERE i.is_low_score)
                   / count(DISTINCT i.order_id) FILTER (WHERE i.has_review)
        FROM model.fact_order_items i JOIN model.dim_seller s USING (seller_id)
        GROUP BY i.seller_id, s.seller_state
        HAVING count(DISTINCT i.order_id) >= 30
        ORDER BY 4 DESC, 3 DESC LIMIT 10
        """).fetchall()],
)
report += [
    f"Sellers with at least 30 orders: {one('SELECT count(*) FROM (SELECT seller_id FROM model.fact_order_items GROUP BY 1 HAVING count(DISTINCT order_id) >= 30)'):,}.",
    "",
]

report += ["## 6. Page 3: by delivery outcome and order size", ""]
report += md_table(
    ["delivery_outcome", "order_size", "Orders", "Low Score Orders", "Low Score Share"],
    [(r[0], r[1], n(r[2]), n(r[3]), pct(r[4])) for r in con.execute(
        """
        SELECT delivery_outcome, order_size, count(*), count(*) FILTER (WHERE is_low_score),
               count(*) FILTER (WHERE is_low_score) / count(*) FILTER (WHERE has_review)
        FROM model.fact_orders
        WHERE delivery_outcome <> 'Unknown'
        GROUP BY delivery_outcome, order_size
        ORDER BY min(delay_band_sort), order_size DESC
        """).fetchall()],
)

report += ["## 7. Page 3: category matrix (table `fact_order_items`, categories with at least 500 orders), top 12 by GMV", ""]
report += md_table(
    ["category_en", "Item GMV", "Item Orders", "Item Low Score Share", "Item Avg Review Score"],
    [(r[0], n(r[1]), n(r[2]), pct(r[3]), f"{r[4]:.2f}") for r in con.execute(
        """
        WITH per_order AS (
            SELECT p.category_en, i.order_id, sum(i.price) AS gmv, max(i.review_score) AS score,
                   bool_or(i.is_low_score) AS low, bool_or(i.has_review) AS reviewed
            FROM model.fact_order_items i JOIN model.dim_product p USING (product_id)
            GROUP BY p.category_en, i.order_id)
        SELECT category_en, sum(gmv), count(*), count(*) FILTER (WHERE low) / count(*) FILTER (WHERE reviewed),
               avg(score)
        FROM per_order GROUP BY category_en HAVING count(*) >= 500 ORDER BY 2 DESC LIMIT 12
        """).fetchall()],
)
report += [f"Item GMV, no filter: {one('SELECT sum(price) FROM model.fact_order_items'):,.2f} (equals GMV).", ""]
item_low_all = one(
    """
    SELECT count(DISTINCT order_id) FILTER (WHERE is_low_score) / count(DISTINCT order_id) FILTER (WHERE has_review)
    FROM model.fact_order_items
    """
)
report += [
    f"Low Score Share (All Categories), the reference line of the matrix: {item_low_all:.1%}. It is slightly lower "
    "than Low Score Share (14.6%) because orders without item rows, which are mostly cancelled or unavailable "
    "orders with many bad reviews, cannot be assigned to a category.",
    "",
]

# %% [markdown]
# ## 3. Complaint categories (table coded_reviews, 300 rows, not related to the other tables)

# %%
with open(ROOT / "review_coding" / "coded_reviews.csv", encoding="utf-8-sig") as handle:
    coded = list(csv.DictReader(handle))
groups = ["On time, single item", "On time, several items", "Late", "Not delivered"]
total_by_group = Counter(r["delivery_group"] for r in coded)
counts = Counter((r["primary_category"], r["delivery_group"]) for r in coded)
categories = [c for c, _ in Counter(r["primary_category"] for r in coded).most_common()]
report += [
    "## 8. Page 3: complaint categories (table `coded_reviews`)",
    "",
    f"Coded Reviews, no filter: {len(coded)}. The table shows `Complaint Share` (share inside the delivery group) "
    "with the number of reviews in brackets.",
    "",
]
report += md_table(
    ["primary_category", "all reviews"] + groups,
    [[c, f"{sum(counts[(c, g)] for g in groups) / len(coded):.1%} ({sum(counts[(c, g)] for g in groups)})"]
     + [f"{counts[(c, g)] / total_by_group[g]:.0%} ({counts[(c, g)]})" for g in groups] for c in categories]
    + [["**Coded Reviews**", f"**{len(coded)}**"] + [f"**{total_by_group[g]}**" for g in groups]],
)

REPORT_PATH.write_text("\n".join(report), encoding="utf-8")
con.close()
print("\n".join(report))
print(f"\nReport written to {REPORT_PATH.relative_to(ROOT)}")
